ARG BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest
FROM $BUILD_FROM

LABEL org.opencontainers.image.source=https://github.com/phil-lipp/hass-addon-newt

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup base
ARG NEWT_VERSION="1.16.0"
ARG BUILD_ARCH
RUN \
    if [ "$BUILD_ARCH" = "aarch64" ]; then \
      curl -o /newt -L -s "https://github.com/fosrl/newt/releases/download/${NEWT_VERSION#v}/newt_linux_arm64"; \
    elif [ "$BUILD_ARCH" = "amd64" ]; then \
      curl -o /newt -L -s "https://github.com/fosrl/newt/releases/download/${NEWT_VERSION#v}/newt_linux_amd64"; \
    fi \
    && chmod a+x /newt

COPY run.sh /
RUN chmod a+x /run.sh

CMD ["/run.sh"]
